apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligence-system-config
  namespace: intelligence-system
  labels:
    app.kubernetes.io/name: intelligence-system
    app.kubernetes.io/component: config
data:
  config.yaml: |
    system:
      name: "AI Intelligence System"
      version: "1.0.0"
      environment: "production"
      debug: false
      log_level: "INFO"
    
    server:
      host: "0.0.0.0"
      port: 8080
      workers: 4
      max_connections: 1000
      timeout_seconds: 30
      enable_cors: true
      cors_origins: ["*"]
    
    database:
      postgres_url: "postgresql://intelligence:${POSTGRES_PASSWORD}@postgres-service:5432/intelligence"
      max_connections: 20
      min_connections: 5
      connection_timeout_seconds: 30
      idle_timeout_seconds: 600
      max_lifetime_seconds: 1800
    
    redis:
      url: "redis://redis-service:6379"
      max_connections: 10
      connection_timeout_seconds: 5
      command_timeout_seconds: 3
    
    kafka:
      bootstrap_servers: ["kafka-service:9092"]
      group_id: "intelligence-system"
      auto_offset_reset: "latest"
      enable_auto_commit: true
      session_timeout_ms: 30000
      heartbeat_interval_ms: 3000
      max_poll_interval_ms: 300000
    
    security:
      jwt_secret: "${JWT_SECRET}"
      jwt_expiry_hours: 24
      encryption_key: "${ENCRYPTION_KEY}"
      rate_limit_requests: 1000
      rate_limit_window_seconds: 3600
      allowed_ips: []
      enable_audit_logging: true
      password_min_length: 12
      password_require_special_chars: true
    
    monitoring:
      prometheus_port: 9090
      jaeger_endpoint: "http://jaeger-service:14268/api/traces"
      log_level: "info"
      enable_tracing: true
      metrics_retention_days: 30
    
    analytics:
      batch_size: 1000
      processing_interval_seconds: 60
      retention_days: 90
      enable_real_time: true
      model_paths:
        sentiment_model: "/models/sentiment"
        classification_model: "/models/classification"
        anomaly_detection_model: "/models/anomaly"
    
    agents:
      max_concurrent_tasks: 100
      task_timeout_seconds: 300
      health_check_interval_seconds: 30
      agent_types:
        intelligence_analyst:
          enabled: true
          max_instances: 5
          resources:
            cpu_limit: "500m"
            memory_limit: "1Gi"
            disk_limit: "2Gi"
          capabilities: ["behavior_analysis", "pattern_recognition", "risk_assessment"]
        threat_hunter:
          enabled: true
          max_instances: 3
          resources:
            cpu_limit: "500m"
            memory_limit: "1Gi"
            disk_limit: "2Gi"
          capabilities: ["threat_detection", "anomaly_detection", "security_analysis"]
        network_analyst:
          enabled: true
          max_instances: 3
          resources:
            cpu_limit: "500m"
            memory_limit: "1Gi"
            disk_limit: "2Gi"
          capabilities: ["network_analysis", "graph_analysis", "community_detection"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligence-system-env
  namespace: intelligence-system
  labels:
    app.kubernetes.io/name: intelligence-system
    app.kubernetes.io/component: environment
data:
  RUST_LOG: "info"
  RUST_BACKTRACE: "1"
  DATABASE_URL: "postgresql://intelligence:${POSTGRES_PASSWORD}@postgres-service:5432/intelligence"
  REDIS_URL: "redis://redis-service:6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  PROMETHEUS_ENDPOINT: "http://prometheus-service:9090"
  JAEGER_ENDPOINT: "http://jaeger-service:14268/api/traces"
